print ("Logika AND")
print ("False and True =", False and True)
print ("False and False =", False and False)
print ("True and False =", True and False)
print ("True and True=", True and True)

print ("Logika OR")
print ("False or True =", False or True)
print ("False or False =", False or False)
print ("True or False =", True or False)
print ("True or True =", True or True)

print ("Logika NOT AND")
print ("not False =",not(False))
print ("not True =",not(True))
