print ("sama dengan == 5")
print (4 == 5)
print ("tidak sama dengan 4! = 5")
print (4!=5)
print ("lebih besar dari 4 > 5")
print (4>5)
print ("lebih kecil dari 4 < 5")
print (4<5)
print ("lebih besar sama dengan 4>=5")
print (4>=5)
print ("lebih kecil sama dengan 4<=5")
print (4<=5)